version: '3.9'
services:
  belab_scraping:
    image: belab_scraping
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app-network
    # Bareun API 서버와의 통신을 위한 443 포트 허용
    ports:
      - "443:443"
    # DNS 설정을 위한 extra_hosts 추가
    extra_hosts:
      - "api.bareun.ai:host-gateway"
    container_name: bemon_scraping  # 원하는 컨테이너 이름
networks:
  app-network:
    driver: bridge
