version: '3.9'
services:
  jupyter:
    container_name: belab_scraping_jupyter
    image: belab_scraping  # Specifies the name for the built image.
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 9999:8888
      - 9001:8000
    depends_on:
      - mongodb
    networks:
      - app-network      
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/app'"      
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: belab_scraping_mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27018:27017
    restart: always
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge      