version: '3.9'
services:
  belab_scraping:
    image: belab_scraping
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # .env 파일에서 환경 변수를 로드
    networks:
      - app-network
    # 필요한 포트와 기타 설정을 여기에 추가하세요
networks:
  app-network:
    driver: bridge
